### ISSUE TITLE
spice-gtk issue in 10.9.5

### ISSUE THREAD

**Issue by mrsmn** [jeffreywildman/homebrew-virt-manager#25]
```
$ brew upgrade
==> Upgrading 1 outdated package, with result:
jeffreywildman/virt-manager/spice-gtk 0.30
==> Upgrading jeffreywildman/virt-manager/spice-gtk
==> Downloading http://www.spice-space.org/download/gtk/spice-gtk-0.30.tar.bz2
######################################################################## 100.0%
==> ./configure --disable-silent-rules --with-gtk=3.0 --enable-introspection --enable-vala --with-audio=no --with-coroutine=gthread --prefix=/usr/local/Cellar/spice-gtk/0.30
==> make install
Last 15 lines from /Users/c0da/Library/Logs/Homebrew/spice-gtk/02.make:
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-recursive
Making install in spice-common
Making install in common
/usr/local/opt/python/bin/python /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice_codegen.py --generate-demarshallers --client --include common/messages.h /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice.proto generated_client_demarshallers.c >/dev/null
/usr/local/opt/python/bin/python /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice_codegen.py --generate-demarshallers --client --include common/messages.h --prefix 1 --ptrsize 8 /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice1.proto generated_client_demarshallers1.c >/dev/null
/usr/local/opt/python/bin/python /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice_codegen.py --generate-marshallers -P --include common/messages.h --include client_marshallers.h --client /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice.proto generated_client_marshallers.c >/dev/null
/usr/local/opt/python/bin/python /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice_codegen.py --generate-marshallers -P --include common/messages.h --include client_marshallers.h --client --prefix 1 --ptrsize 8 /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice1.proto generated_client_marshallers1.c >/dev/null
make[3]: *** [generated_client_demarshallers1.c] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [generated_client_demarshallers.c] Error 1
make[3]: *** [generated_client_marshallers1.c] Error 1
make[3]: *** [generated_client_marshallers.c] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues
```

Cheers

**Comment by ssdgithub** [comment]
Same issue...

**Comment by ppacory** [comment]
$ brew install virt-manager
==> Installing virt-manager from jeffreywildman/homebrew-virt-manager
==> Installing dependencies for jeffreywildman/virt-manager/virt-manager: libsoup-with-gnome, spice-gtk, gnome-icon-theme
==> Installing jeffreywildman/virt-manager/virt-manager dependency: libsoup-with-gnome
==> Downloading https://download.gnome.org/sources/libsoup/2.52/libsoup-2.52.0.tar.xz
Already downloaded: /Library/Caches/Homebrew/libsoup-with-gnome-2.52.0.tar.xz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libsoup-with-gnome/2.52.0 --disable-tls-check
==> make install
🍺  /usr/local/Cellar/libsoup-with-gnome/2.52.0: 195 files, 5,7M, built in 17 seconds
==> Installing jeffreywildman/virt-manager/virt-manager dependency: spice-gtk
==> Downloading http://www.spice-space.org/download/gtk/spice-gtk-0.30.tar.bz2
Already downloaded: /Library/Caches/Homebrew/spice-gtk-0.30.tar.bz2
==> ./configure --disable-silent-rules --with-gtk=3.0 --enable-introspection --enable-vala --with-audio=no --with-coroutine=gthread --prefix=/usr/local/Cellar/spice-gtk/0.30
==> make install
Last 15 lines from /Users/ppacory/Library/Logs/Homebrew/spice-gtk/02.make:
/usr/local/opt/python/bin/python /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice_codegen.py --generate-marshallers -P --include common/messages.h --include client_marshallers.h --client --prefix 1 --ptrsize 8 /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice1.proto generated_client_marshallers1.c >/dev/null
/usr/local/opt/python/bin/python /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice_codegen.py --generate-demarshallers --server --include common/messages.h /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice.proto generated_server_demarshallers.c >/dev/null
/usr/local/opt/python/bin/python /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice_codegen.py --generate-marshallers -M String -M Rect -M Point -M DisplayBase -M Fill -M Opaque -M Copy -M Blend -M Blackness -M Whiteness -M Invers -M Rop3 -M Stroke -M Text -M Transparent -M AlphaBlend -M Composite --server --include common/messages.h /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice.proto generated_server_marshallers.c >/dev/null
/usr/local/opt/python/bin/python /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice_codegen.py --generate-marshallers -M String -M Rect -M Point -M DisplayBase -M Fill -M Opaque -M Copy -M Blend -M Blackness -M Whiteness -M Invers -M Rop3 -M Stroke -M Text -M Transparent -M AlphaBlend -M Composite --server --include common/messages.h -H /usr/local/Cellar/spice-protocol/0.12.10/lib/spice-protocol/spice.proto generated_server_marshallers.h >/dev/null
make[3]: *** [generated_server_demarshallers.c] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [generated_client_demarshallers1.c] Error 1
make[3]: *** [generated_client_marshallers.c] Error 1
make[3]: *** [generated_server_marshallers.c] Error 1
make[3]: *** [generated_client_demarshallers.c] Error 1
make[3]: *** [generated_server_marshallers.h] Error 1
make[3]: *** [generated_client_marshallers1.c] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

**Comment by jmrgn** [comment]
Yep. I got this issue as well.

```
Last 15 lines from /Users/jamrgn/Library/Logs/Homebrew/spice-gtk/02.make:
 : portErrorNoNo module named six
o module named six

ImportError: No module named six
make[3]: *** [generated_server_marshallers.h] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [generated_server_marshallers.c] Error 1
make[3]: *** [generated_server_demarshallers.c] Error 1
make[3]: *** [generated_client_marshallers1.c] Error 1
make[3]: *** [generated_client_marshallers.c] Error 1
make[3]: *** [generated_client_demarshallers1.c] Error 1
make[3]: *** [generated_client_demarshallers.c] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

```

**Comment by jeffreywildman** [comment]
Sorry, I'm unable to confirm due to using a newer OS X.  Does a verbose build, ```brew install -v```, yield any additional clues?

**Comment by ssdgithub** [comment]
Steps to resolve problem
- upgrade to yosemite
- brew update
- brew upgrade
- brew install virt-manager

**Comment by codebauss** [comment]
Unfortunately the "steps to resolve problem" did not work for me. I was able to resolve however via details from spice-gtk mailing list:

http://lists.freedesktop.org/archives/spice-devel/2012-April/008849.html
pip install pyparsing

This resulted in successful installation of virt-manager.

**Comment by mrsmn** [comment]
Hi again,

@codebauss your trick worked indeed:
```
[mrsmn@outcast ~]$ $ /usr/local/Cellar/python/2.7.10_2/bin/pip install pyparsing
Collecting pyparsing
    Downloading pyparsing-2.0.5-py2.py3-none-any.whl
Installing collected packages: pyparsing
Successfully installed pyparsing-2.0.5
[mrsmn@outcast ~]$ $ brew update && brew upgrade
Already up-to-date.
==> Upgrading 1 outdated package, with result:
jeffreywildman/virt-manager/spice-gtk 0.30
==> Upgrading jeffreywildman/virt-manager/spice-gtk
==> Downloading http://www.spice-space.org/download/gtk/spice-gtk-0.30.tar.bz2
Already downloaded: /Library/Caches/Homebrew/spice-gtk-0.30.tar.bz2
==> ./configure --disable-silent-rules --with-gtk=3.0 --enable-introspection --enable-vala --with-audio=no --with-coroutine=gthread --prefix=/usr/local/Cellar/spice-gtk/0.30
==> make install
🍺  /usr/local/Cellar/spice-gtk/0.30: 97 files, 3.2M, built in 52 seconds
```
@jeffreywildman Should pyparsing be added as a dependency?

Cheers.

**Comment by jeffreywildman** [comment]
@mrsmn After some digging, it seems that pyparsing is technically a build dependency of spice-gtk, but the developers have gone out of their way to distribute pre-generated files so that pyparsing is not needed by end users.  Tracing the source code from spice-gtk to spice-common (which is bundled with spice-gtk), the comments are in [here](http://cgit.freedesktop.org/spice/spice-common/tree/common/Makefile.am?id=dd63a3b).

Using a homebrewed python, I checked to make sure pyparsing was not already present on my system, was able to successfully compile spice-gtk, and afterward checked again to ensure that pyparsing was not found by python.

I don't fully understand the internals of ```brew upgrade``` vs ```brew install```, but perhaps the former is causing the error?  If anyone hasn't yet installed pyparsing as a workaround, I'd suggest trying to remove spice-gtk first and then attempting an install to test the upgrade/install hypothesis:

```
brew remove spice-gtk
brew install spice-gtk
```

**Comment by codebauss** [comment]
I had to use homebrew python but this was installed after successfully installing virt-manager because I kept getting an error along the lines of python2 not found. I am not sure either of the differences but I would suggest that anyone running into this issue ensure they have python installed via homebrew, try to install virt-manager, and then if that does not work because of the spice-gtk issue, install pyparsing if you run into the same issue as outlined here.

**Comment by jeffreywildman** [comment]
@codebauss The python2 issue is due to the shebangs at the top of the python programs distributed by virt-manager.  The OSX python installation (on my system at least) does not include a symlink ```/usr/bin/python2```, meaning virt-manager can't find python in order to run.  On the other hand, the homebrewed python does install python2 symlinks (in ```/usr/local/bin```), allowing virt-manager to run.

@mrsmn Interestingly, the OSX system python *does* ship with the pyparsing module already installed (in ```/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/```).  Enabling the system python to work with these formulas should be one way to work-around the issue.

Connecting this with #6, I am tempted to update the main branch to support installs using the system python (or rather with whichever python is found in the user's path), but am not sure how disruptive it will be to existing virt-manager installations.  They should carry along fine, but if the user switches which python is available in the path, a complete reinstall of virt-manager and dependencies may be necessary.

**Comment by mrsmn** [comment]
@jeffreywildman If you push the changes to master I'll happilly test it.

**Comment by jeffreywildman** [comment]
@mrsmn Thanks, pushed to master.
