### ISSUE TITLE
Virt-viewer can't open display

### ISSUE THREAD

**Issue by lbkNhubert** [jeffreywildman/homebrew-virt-manager#36]
I am able to connect and get a list of running machines, but when attempting to connect to the VM I receive the following message:

(virt-viewer:24560): GSpice-WARNING **: main-1:0: could not set sockopt TCP_NODELAY: Operation not supported on socket

**Comment by jeffreywildman** [comment]
Hi, I am able to confirm similar warnings when connecting to a SPICE display of a VM. Additionally, connecting to a VM's SPICE display using ```virt-viewer``` was initially met with repeated authentication requests (via command line) that were unsuccessful. However, I was able to successfully connect and open a SPICE display by taking the following steps:

1) I used virt-manager to change settings on a VM to use a Spice Display instead of a VNC Display.
2) The Spice Display was configured to listen on *all interfaces* (as opposed to *localhost only*).
3) The option ```--direct``` was supplied to subsequent invocations of ```virt-viewer```.

Let me know if this helps. Also, I can't comment on whether this represents best practices with regards to VM security, though it does look like a password can be set for incoming SPICE display connections. Perhaps someone can chime in on proper VM configuration and SPICE display usage.

**Comment by lbkNhubert** [comment]
Thanks, I was able to connect to the VM using the --direct option.

**Comment by etscript** [comment]
thanks

**Comment by Yash-Ambavade** [comment]
@jeffreywildman I am using a Mac and I am getting the same error on terminal while trying to run the virtual machine. The display won't open. Could you please elaborate on the steps to change it to SPICE display instead of VNC display.
