### ISSUE TITLE
Unable to connect to remote libvirt

### ISSUE THREAD

**Issue by i7clock** [jeffreywildman/homebrew-virt-manager#37]
Here is a traceback:
I am new to virt-manager so I don't know if this is an issue but I can connect to the server on Debian.

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.3.1/libexec/share/virt-manager/virtManager/connection.py", line 903, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/local/Cellar/virt-manager/1.3.1/libexec/share/virt-manager/virtinst/connection.py", line 148, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/1.3.1/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: An error occurred, but the cause is unknown

**Comment by jeffreywildman** [comment]
Hi, what is the command (with options, redacted if necessary) that you are running? This error message looks related to authentication issues. You may need to supply [--no-fork or --debug](https://github.com/jeffreywildman/homebrew-virt-manager/blob/master/README.md#notes) to get SSH password prompts to display, or set up SSH keys.

**Comment by i7clock** [comment]
Thanks for the quick reply. I try to connect via the gui in virt-manager.

File>AddConnection

Hypervisor QEMU/KVM
Method SSH
user ****
hostname ****

**Comment by jeffreywildman** [comment]
What is the form of the Libvirt URI you are using? Perhaps try connecting to the same Libvirt URI using the command ```virsh```? If you can't connect using ```virsh```, then the problem may be localized to the URI.

**Comment by i7clock** [comment]
the uri is just an ip address/system ok i'll try virsh thx :D

**Comment by jeffreywildman** [comment]
Also see the [Readme](https://github.com/jeffreywildman/homebrew-virt-manager#notes) for notes on socket location overriding.

**Comment by i7clock** [comment]
now I get this with virsh and virt-manager -c ***:
error: authentication failed: unsupported authentication type 2

**Comment by xvladi** [comment]
I have the same error with virt-manager like you. 

Same URI with virsh:
```
$ virsh -c qemu+ssh://user@host/system
error: failed to connect to the hypervisor
error: An error occurred, but the cause is unknown
```

using 
```
$ virsh -c qemu+ssh://user@host/system?socket=/var/run/libvirt/libvirt-sock
Welcome to virsh, the virtualization interactive terminal.

Type:  'help' for help with commands
       'quit' to quit

virsh #
```
according to the Readme works.

Same success with virt-manager:
```
virt-manager -c qemu+ssh://user@host/system?socket=/var/run/libvirt/libvirt-sock
```

(virt-manager@OSX 10.11 -> libvirtd@centos7)

**Comment by sklav** [comment]
similar issue using virsh from mac. the solution seems to be to run sudo before the command.

example: sudo virsh -c  connect-string list  seems to work for me also make sure root has ssh key copied over. maybe not the best solution but works for me till something better comes along.

**Comment by i7clock** [comment]
ssh keys are copied and i can do a normal ssh login with both root and the user i want to use for virt-manager. the problem i have now encountered is that the user apparently does not have the rights to use libvirtd... and it doesnt help to be part of the group libvirtd... i need to configure polkit to access virsh from the normal user. here is a helpful link addressing this problem: 
http://www2.linuxsysadmintutorials.com/configure-polkit-to-run-virsh-as-a-normal-user/
although there seems to be a problem with the if statement as the comments describe below.
I hope this helps! I have not configured it yet due to maintenance work on the server, but I will work on it asap. Merry christmas and happy celebrating!

**Comment by Venomen** [comment]
There is simple solution ;). In my case, I had to run it from console and use debug.. so I could write and use password!! :X :d don't ask why, it just don't work from program menu.. OS X El Capitan, all installed from brew.

virt-manager -c "qemu+ssh://h4ck3r@192.168.1.100:6666/system?socket=/var/run/libvirt/libvirt-sock" --debug

**Comment by i7clock** [comment]
Thanks a lot worked for me too! Shall I close this? Or is it still considered an issue?

Greetings,
i7clock

**Comment by Venomen** [comment]
I think it should be repaired cause you can't use password in popup menu in program gui.

**Comment by jeffreywildman** [comment]
On Ubuntu, `openssh-askpass` provides the graphical prompt for SSH passwords when using `virt-manager`. After a quick search, it does not appear that this dependency is readily available for OSX, possibly due to different keychain management (outside my area of knowledge). However, during installation, `virt-manager` may be pointed to a suitable replacement with the `--askpass-package-names=` option to `setup.py`. Time permitting, this should be pushed upstream.

**Comment by toddpfaff** [comment]
I was having the "libvirtError: An error occurred, but the cause is unknown" problem and some searching lead me to the solution mentioned above - adding the ?socket argument to the connection URI string.  That solved the problem for me in the case of a simple virsh command or a virt-manager connection to a single remote libvirtd.

Does anyone know how to then get virt-manager to use such strings in connections?  I'm not talking about the case where one runs virt-manager with a connection URI on the command line, but rather the case where one wants to create multiple remote libvirt connections from one virt-manager connection using the virt-manager File, Add connection dialog.  The Generated URI will be of the form qemu+ssh://Username@Hostname/system, but we need this to have the ?socket string appended in order to work around the problem discussed above.

I also know that on a linux system virt-manager uses dconf to store connection URIs at path [org/virt-manager/virt-manager/connections] in the file typically found in ~/.config/dconf/user.

Does virt-manager on MacOS use dconf?  If not, where does it store connection URIs?  Once I know that I can try to enter them manually with the ?socket string appended.

Alternatively, is there another solution to this problem that doesn't require the ?socket string?

**Comment by Moep90** [comment]
Added an Alias
`
alias virt-manager="virt-manager -c qemu+ssh://usr@hostname:port/system?socket=/var/run/libvirt/libvirt-sock"
`
