### ISSUE TITLE
brew install virt-manager issue

### ISSUE THREAD

**Issue by arowley0** [jeffreywildman/homebrew-virt-manager#58]
It seems similar to issue[#43](https://github.com/jeffreywildman/homebrew-virt-manager/issues/43)

I updated xcode and brew and still I cannot install virt manager.

> /usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
> /usr/local/opt/python/bin/python2.7 generator.py libvirt /usr/local/Cellar/libvirt/2.2.0/share/libvirt/api/libvirt-api.xml
> Found 415 functions in /usr/local/Cellar/libvirt/2.2.0/share/libvirt/api/libvirt-api.xml
> Found 0 functions in libvirt-override-api.xml
> Generated 344 wrapper functions
> Missing type converters: 
> virConnectNodeDeviceEventGenericCallback:1 
> ERROR: failed virConnectNodeDeviceEventRegisterAny
> error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1

**Comment by mrsmn** [comment]
@arowley0 have a look at #57, the workaround seems to fix the issue.

**Comment by ki-media** [comment]
Same here. BTW the workaround in #57 is not working (anymore). A working solution is recommended.

**Comment by fkpwolf** [comment]
same issue here, after upgrade to macOS Sierra.

**Comment by Ryuchen** [comment]
Change the file of virt-manager.rb, as follow:

class VirtManager < Formula
  desc "App for managing virtual machines"
  homepage "https://virt-manager.org/"
  url "https://fedorahosted.org/released/virt-manager/virt-manager-1.4.0.tar.gz"
  sha256 "bf31a40cc48500cbf87a0e93a5838fc3f6ce4e2fa03f8bce6aa2615625e6caca"

  depends_on "intltool" => :build
  depends_on "pkg-config" => :build

  depends_on "dbus"
  depends_on "gnome-icon-theme"
  depends_on "gtk+3"
  depends_on "gtk-vnc"
  depends_on "hicolor-icon-theme"
  depends_on "libosinfo"
  depends_on "libvirt"
  depends_on "libvirt-glib"
  depends_on "libxml2" => "with-python"
  depends_on "pygobject3"
  depends_on "spice-gtk"
  depends_on "vte3"
  depends_on :x11
  # TODO: audio

  resource "libvirt-python" do
    url "https://libvirt.org/sources/python/libvirt-python-2.2.0.tar.gz"
    sha256 "ba6b2eb3f018275e9720498d7b771959c2d51ebd54f6e956de5055f912afea76"
  end

  resource "requests" do
    url "https://pypi.python.org/packages/source/r/requests/requests-2.9.1.tar.gz"
    sha256 "c577815dd00f1394203fc44eb979724b098f88264a9ef898ee45b8e5e9cf587f"
  end

  resource "ipaddr" do
    url "https://pypi.python.org/packages/source/i/ipaddr/ipaddr-2.1.11.tar.gz"
    sha256 "1b555b8a8800134fdafe32b7d0cb52f5bdbfdd093707c3dd484c5ea59f1d98b7"
  end

  patch :DATA # OS X does not conform to PEP 394, python2 symlink missing

  def install
    # update location of cpu_map.xml
    # https://github.com/jeffreywildman/homebrew-virt-manager/issues/15
    inreplace "virtinst/capabilities.py", "/usr/share/libvirt/cpu_map.xml", "#{HOMEBREW_PREFIX}/share/libvirt/cpu_map.xml"

    ENV.prepend_create_path "PYTHONPATH", "#{libexec}/vendor/lib/python2.7/site-packages"
    %w[libvirt-python requests ipaddr].each do |r|
      resource(r).stage { system "python", *Language::Python.setup_install_args(libexec/"vendor") }
    end

    ENV.prepend_path "PYTHONPATH", "#{Formula["libxml2"].opt_lib}/python2.7/site-packages"

    system "python", "setup.py",
                     "configure",
                     "--prefix=#{libexec}"
    system "python", "setup.py",
                     "--no-user-cfg",
                     "--no-update-icon-cache",
                     "--no-compile-schemas",
                     "install",
                     "--prefix=#{libexec}"

    bin.install Dir[libexec/"bin/*"]
    bin.env_script_all_files(libexec/"bin", :PYTHONPATH => ENV["PYTHONPATH"])

    # install and link schemas
    share.install Dir[libexec/"share/glib-2.0"]

    # install and link icons
    share.install Dir[libexec/"share/icons"]
  end

  def post_install
    # manual schema compile step
    system "#{Formula["glib"].opt_bin}/glib-compile-schemas", "#{HOMEBREW_PREFIX}/share/glib-2.0/schemas"
    # manual icon cache update step
    system "#{Formula["gtk+3"].opt_bin}/gtk3-update-icon-cache", "#{HOMEBREW_PREFIX}/share/icons/hicolor"
  end
end
__END__
diff --git a/virt-clone b/virt-clone
index 4bd5ca3..6b4b9e5 100755
--- a/virt-clone
+++ b/virt-clone
@@ -1,4 +1,4 @@
-#!/usr/bin/env python2
+#!/usr/bin/env python
 #
 # Copyright(c) FUJITSU Limited 2007.
 #
diff --git a/virt-convert b/virt-convert
index a7f9a97..2f1ca7a 100755
--- a/virt-convert
+++ b/virt-convert
@@ -1,4 +1,4 @@
-#!/usr/bin/env python2
+#!/usr/bin/env python
 #
 # Copyright 2008, 2013, 2014  Red Hat, Inc.
 # Joey Boggs <jboggs@redhat.com>
diff --git a/virt-install b/virt-install
index 45607fb..4f9cf9e 100755
--- a/virt-install
+++ b/virt-install
@@ -1,4 +1,4 @@
-#!/usr/bin/env python2
+#!/usr/bin/env python
 #
 # Copyright 2005-2014 Red Hat, Inc.
 #
diff --git a/virt-manager b/virt-manager
index d352b90..5fccceb 100755
--- a/virt-manager
+++ b/virt-manager
@@ -1,4 +1,4 @@
-#!/usr/bin/env python2
+#!/usr/bin/env python
 #
 # Copyright (C) 2006, 2014 Red Hat, Inc.
 # Copyright (C) 2006 Daniel P. Berrange <berrange@redhat.com>
diff --git a/virt-xml b/virt-xml
index 4e0848c..eb40bfa 100755
--- a/virt-xml
+++ b/virt-xml
@@ -1,4 +1,4 @@
-#!/usr/bin/env python2
+#!/usr/bin/env python
 #
 # Copyright 2013-2014 Red Hat, Inc.
 # Cole Robinson <crobinso@redhat.com>

**Comment by Ryuchen** [comment]
Change the file of virt-manager.rb, as follow:

  resource "libvirt-python" do
    url "https://libvirt.org/sources/python/libvirt-python-2.2.0.tar.gz"
    sha256 "ba6b2eb3f018275e9720498d7b771959c2d51ebd54f6e956de5055f912afea76"
  end

**Comment by ki-media** [comment]
It installs correct. But now when I try to start  libgdk-3.0.dylib crashes... Already tried to completly rebuild with no success...

**Comment by danifunker** [comment]
I have the same issue as you @ki-media, but weird enough virt-manager --debug works fine.

**Comment by danifunker** [comment]
Ended up creating an AppleScript "application" in my /Applications folder, here is the contents if anybody wants...

do shell script "/usr/local/bin/virt-manager --debug > /dev/null 2>&1 &"

Now it works and I have an icon. Yay for me

**Comment by ki-media** [comment]
This did the trick! Weird but works! Many thanks @danifunker

**Comment by hit0wnzzz** [comment]
@Ryuchen that worked for me, location of the file for me was:

`/usr/local/Homebrew/Library/Taps/jeffreywildman/`

**Comment by 66Ton99** [comment]
`nano +26 /usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb`

Change to:
```
 resource "libvirt-python" do
    url "https://libvirt.org/sources/python/libvirt-python-2.3.0.tar.gz"
    sha256 "ad25a98c2508a6c81d65cc8bc5f3e0b4c506247cf544a7d54c41526a99caef48"
  end
```

**Comment by Nethe** [comment]
Worked! Virt-manager has been installed successfully! Thanks!

**Comment by kode54** [comment]
And now, it also works with libvirt-python-2.4.0.

**Comment by efij** [comment]
using macOS Sierra. 
still getting an error while trying to run:
> brew install virt-manager virt-viewer

This is the output:

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-mana
Already downloaded: /Users/efij/Library/Caches/Homebrew/virt-manager-1.4.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-2.3.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cel
Last 15 lines from /Users/efij/Library/Logs/Homebrew/virt-manager/01.python:
Generated 350 wrapper functions
Missing type converters: 
virConnectSecretEventGenericCallback:1 
virStreamSourceFunc:1 
virStreamSinkFunc:1 
unsigned long long *:1 
virStorageVolInfoPtr:1 
long long *:1 
ERROR: failed virConnectSecretEventRegisterAny
ERROR: failed virDomainMigrateGetMaxDowntime
ERROR: failed virStorageVolGetInfoFlags
ERROR: failed virStreamRecvHole
ERROR: failed virStreamSparseRecvAll
ERROR: failed virStreamSparseSendAll
error: command '/usr/bin/python' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
virt-manager silently quits at launch https://github.com/jeffreywildman/homebrew-virt-manager/issues/78
installation failure for virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/72
Error: jeffreywildman/virt-manager/libvirt-glib 1.0.0 did not build https://github.com/jeffreywildman/homebrew-virt-manager/issues/79
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
Add necessary quotes https://github.com/jeffreywildman/homebrew-virt-manager/pull/75
ERROR: failed virDomainMigrateGetMaxDowntime error: command '/usr/bin/python' failed with exit status 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/81
Installation fails: Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime https://github.com/jeffreywildman/homebrew-virt-manager/issues/80
missing module gi https://github.com/jeffreywildman/homebrew-virt-manager/issues/76
gi has no attribute 'require_version' https://github.com/jeffreywildman/homebrew-virt-manager/issues/74
Installation fails: Missing type converters https://github.com/jeffreywildman/homebrew-virt-manager/issues/71
Unable to paste from host to client. Copying from client to host works. https://github.com/jeffreywildman/homebrew-virt-manager/issues/35
Unable to connect to libvirt https://github.com/jeffreywildman/homebrew-virt-manager/issues/63
 libvirt-glib wont build - OSError: [Errno 1] Operation not permitted: g-ir-scanner/ https://github.com/jeffreywildman/homebrew-virt-manager/issues/82
libvirt connection URI ?socket string https://github.com/jeffreywildman/homebrew-virt-manager/issues/61
Can't install libvirt-python on El Capitan https://github.com/jeffreywildman/homebrew-virt-manager/issues/50
Install error: failed virConnectNodeDeviceEventRegisterAny https://github.com/jeffreywildman/homebrew-virt-manager/issues/57
Create new virtual machine OS types missing https://github.com/jeffreywildman/homebrew-virt-manager/issues/64
Error: configure: error: libjpeg not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/49
after brew update  , the same error https://github.com/jeffreywildman/homebrew-virt-manager/issues/55
Crash on re-open VNC console https://github.com/jeffreywildman/homebrew-virt-manager/issues/44
Install error: [LibvirtGLib-1.0.gir] Error 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/77
Fresh install on 10.11.1: fatal error: 'glib/gi18n-lib.h' file not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/30
Unable to install due to missing six python module. https://github.com/jeffreywildman/homebrew-virt-manager/issues/68
Python quit unexpectedly every time I try and select a drop down box. https://github.com/jeffreywildman/homebrew-virt-manager/issues/45
Docs update about remote connections https://github.com/jeffreywildman/homebrew-virt-manager/issues/42
Error installing spice-gtk: No package 'spice-client-glib-2.0' found https://github.com/jeffreywildman/homebrew-virt-manager/issues/56

**Comment by jeffreywildman** [comment]
Closing as this was likely due to a mismatch between libvirt and libvirt-python versions, now match at 4.0.0 in latest virt-manager and libvirt formulae.
